import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import { playfair, oswald } from "./fonts";

export const metadata: Metadata = {
  title: "Tourist App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${playfair.variable} ${oswald.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
